import type { Config } from 'tailwindcss';

export default {
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        card: 'var(--card)',
        'card-muted': 'var(--card-muted)',
        border: 'var(--border)',
        muted: 'var(--muted)',
        'muted-foreground': 'var(--muted-foreground)',
        primary: 'var(--primary)',
        'primary-hover': 'var(--primary-hover)',
        'primary-soft': 'var(--primary-soft)',
        'primary-subtle': 'var(--primary-soft)',
        'primary-foreground': 'var(--primary-foreground)',
        accent: 'var(--accent)',
        'accent-soft': 'var(--accent-soft)',
        'accent-text': 'var(--accent-text)',
        success: 'var(--success)',
        'success-soft': 'var(--success-soft)',
        'success-text': 'var(--success-text)',
        warning: 'var(--warning)',
        'warning-soft': 'var(--warning-soft)',
        destructive: 'var(--destructive)',
        'destructive-fill': 'var(--destructive-fill)',
        'destructive-fill-foreground': 'var(--destructive-fill-foreground)',
        'destructive-soft': 'var(--destructive-soft)',
        'destructive-text': 'var(--destructive-text)',
        'on-color': 'var(--on-color)',
        'border-strong': 'var(--border-strong)',
        'surface-raised': 'var(--surface-raised)',
        ring: 'var(--ring)',
        surface: 'var(--surface)',
        outline: 'var(--outline)',
        'tint-blue': 'var(--tint-blue)',
        'tint-slate': 'var(--tint-slate)',
        'tint-green': 'var(--tint-green)',
        'tint-red': 'var(--tint-red)',
        'tint-foreground': 'var(--tint-foreground)',
      },
      borderRadius: {
        xs: 'var(--radius-xs)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
      },
      transitionTimingFunction: {
        out: 'var(--ease-out)',
        spring: 'var(--ease-spring)',
      },
      transitionDuration: {
        fast: 'var(--dur-fast)',
        base: 'var(--dur-base)',
        slow: 'var(--dur-slow)',
      },
      fontFamily: {
        sans: 'var(--font-sans), system-ui, sans-serif',
        display: 'var(--font-display), system-ui, sans-serif',
        mono: 'var(--font-mono), ui-monospace, monospace',
      },
      boxShadow: {
        sm: 'var(--shadow-sm, 0 1px 2px 0 rgb(0 0 0 / 0.05))',
        md: 'var(--shadow-md, 0 4px 6px -1px rgb(0 0 0 / 0.1))',
        lg: 'var(--shadow-lg, 0 10px 15px -3px rgb(0 0 0 / 0.1))',
        glow: 'var(--shadow-glow)',
        'hard-sm': 'var(--shadow-hard-sm)',
        hard: 'var(--shadow-hard)',
        'hard-lg': 'var(--shadow-hard-lg)',
      },
    },
  },
  plugins: [],
} satisfies Config;
